baseURL = "https://frikyfriky11.github.io/"
title = "frikyfriky11"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "dracula"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Stefano Previato"
license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Stefano Previato's personal website"
keywords = "blog,developer,personal,software engineer"
info = ["Full Stack Senior Software Engineer"]
avatarURL = "images/avatar.jpg"
dateFormat = "January 2, 2006"
since = 2019
commit = "https://github.com/frikyfriky11/frikyfriky11.github.io/tree/main"
rtl = false
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5
customCSS = []
customSCSS = []
customJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/frikyfriky11/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 3
url = "https://twitter.com/frikyfriky11/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/stefano-previato/"

[[params.social]]
name = "RSS"
icon = "fa fa-2x fa-rss"
weight = 6
url = "http://localhost:1313/index.xml"
rel = "alternate"
type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "Posts"
weight = 1
url = "posts/"

[[languages.en.menu.main]]
name = "Categories"
weight = 2
url = "categories/"

[[languages.en.menu.main]]
name = "Tags"
weight = 3
url = "tags/"

[[languages.en.menu.main]]
name = "About me"
weight = 4
url = "about/"
