{
 "title": "Generale",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Flussi di energia", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Modalità batteria inverter",
   "type": "stat",
   "description": "Indica la modalità attuale della batteria inverter\n\nI valori possibili sono:\n\n- disabled\n- normal\n- service\n- charge boost\n- nearly depleted\n- suspended\n- calibrate\n- grid support\n- deplete recovery\n- non operable (voltage)\n- non operable (temperature)\n- preheating\n- startup\n- stopped (temperature)\n- battery full",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerflow_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"inverter_battery_mode\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Modalità backup",
   "type": "stat",
   "description": "Indica la modalità attuale di backup del sistema",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerflow_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"site_backup_mode\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Standby batteria",
   "type": "stat",
   "description": "Indica se attualmente la batteria è in standby",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerflow_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"site_battery_standby\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Luogo contatore",
   "type": "stat",
   "description": "Indica dove è attualmente montato il contatore di energia\n\nI valori possibili sono:\n\n- load\n- grid\n- unknown (during backup power)",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerflow_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"site_meter_location\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Modalità configurazione",
   "type": "stat",
   "description": "Indica in quale modalità è attualmente configurato l'impianto\n\nI valori possibili sono:\n\n- \"produce -only\" (inverter only)\n- \"meter\", \"vague -meter\" (inverter and meter)\n- \"bidirectional\", \"ac -coupled\" (inverter, meter and battery)",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerflow_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"site_mode\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Flusso batteria nel tempo (+ carica, - scarica)",
   "type": "timeseries",
   "description": "Indica il flusso di potenza della batteria nel corso del tempo\n\nUn valore negativo indica che la batteria sta cedendo corrente (*si sta scaricando*), un valore positivo indica che la batteria sta ottenendo corrente (*si sta caricando*)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerflow_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"site_power_batteries_w\")\r\n  |> map(fn: (r) => ({ r with _value: r._value * -1.0 }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Flusso rete nel tempo (+ vende, - compra)",
   "type": "timeseries",
   "description": "Indica il flusso di potenza della rete nel corso del tempo\n\nUn valore negativo indica che la rete sta fornendo corrente (*si sta comprando*), un valore positivo indica che la rete sta ottenendo corrente (*si sta vendendo*)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerflow_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"site_power_grid_w\")\r\n  |> map(fn: (r) => ({ r with _value: r._value * -1.0 }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Flusso fotovoltaico nel tempo",
   "type": "timeseries",
   "description": "Indica il flusso di potenza dei pannelli fotovoltaici nel corso del tempo",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerflow_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"site_power_panels_w\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Flusso consumi nel tempo",
   "type": "timeseries",
   "description": "Indica il flusso di potenza consumata nel corso del tempo",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerflow_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"site_power_load_w\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Batteria", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Carica relativa attuale",
   "type": "bargauge",
   "description": "Indica quanto è carica la batteria in questo momento",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"storage_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"charging_state_relative_percent\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Potenza assoluta attuale",
   "type": "stat",
   "description": "Indica quanto è carica la batteria in questo momento",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"storage_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"capacity_maximum_w\" or r[\"_field\"] == \"charging_state_relative_percent\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with _value: r.capacity_maximum_w * r.charging_state_relative_percent / 100.00 }))\r\n  |> drop(columns: [\"charging_state_relative_percent\", \"capacity_maximum_w\"])\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Capacità massima",
   "type": "stat",
   "description": "Indica a quanto ammonta la capacità massima della batteria",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"storage_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"capacity_maximum_w\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Capacità massima teorica",
   "type": "stat",
   "description": "Indica a quanto ammonta la capacità massima teorica della batteria",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"storage_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"designed_capacity_w\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Numero di serie",
   "type": "stat",
   "description": "Numero di serie della batteria",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"storage_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"serial\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "stat",
   "description": "Temperatura attuale della batteria",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"storage_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature_cell_c\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Tensione",
   "type": "stat",
   "description": "Tensione attuale della batteria",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"storage_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage_dc_v\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Corrente",
   "type": "stat",
   "description": "Corrente attuale della batteria\n\nUn valore negativo indica che la batteria sta cedendo corrente (*si sta scaricando*), un valore positivo indica che la batteria sta ottenendo corrente (*si sta caricando*)",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"storage_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_dc_a\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Produttore",
   "type": "stat",
   "description": "Produttore/marca della batteria",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"storage_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"manufacturer\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Modello",
   "type": "stat",
   "description": "Modello della batteria",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"storage_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"model\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Stato",
   "type": "stat",
   "description": "Indica lo stato della batteria",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"storage_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"battery_cell_status\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Attiva",
   "type": "stat",
   "description": "Indica se la batteria è attualmente attiva",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"storage_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"enable\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Carica relativa nel tempo",
   "type": "timeseries",
   "description": "Indica la carica relativa della batteria nel corso del tempo",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"storage_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"charging_state_relative_percent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Corrente nel tempo",
   "type": "timeseries",
   "description": "Indica la corrente della batteria nel corso del tempo\n\nUn valore negativo indica che la batteria sta cedendo corrente (*si sta scaricando*), un valore positivo indica che la batteria sta ottenendo corrente (*si sta caricando*)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"storage_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_dc_a\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperatura nel tempo",
   "type": "timeseries",
   "description": "Indica la temperatura della batteria nel corso del tempo",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"storage_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature_cell_c\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Potenza nel tempo",
   "type": "timeseries",
   "description": "Indica la potenza della batteria nel corso del tempo",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"storage_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"capacity_maximum_w\" or r[\"_field\"] == \"charging_state_relative_percent\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with _value: r.capacity_maximum_w * r.charging_state_relative_percent / 100.00 }))\r\n  |> drop(columns: [\"charging_state_relative_percent\", \"capacity_maximum_w\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Tensione nel tempo",
   "type": "timeseries",
   "description": "Indica la tensione della batteria nel corso del tempo",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"storage_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage_dc_v\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Inverter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Frequenza di rete AC",
   "type": "stat",
   "description": "Frequenza attuale della rete in corrente alternata",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"fac_ac_frequency_hz\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Tensione rete AC",
   "type": "stat",
   "description": "Tensione attuale della rete in corrente alternata",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uac_ac_voltage_v\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Potenza rete AC",
   "type": "stat",
   "description": "Potenza attuale della rete in corrente alternata",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pac_ac_power_w\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Corrente rete AC",
   "type": "stat",
   "description": "Corrente attuale della rete in corrente alternata",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"iac_ac_current_a\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Stato",
   "type": "stat",
   "description": "Stato attuale dell'inverter",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"devicestatus_inverterstate\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Codice di stato",
   "type": "stat",
   "description": "Codice di stato attuale dell'inverter",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"devicestatus_statuscode\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Codice di errore",
   "type": "stat",
   "description": "Codice di errore attuale dell'inverter",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"devicestatus_errorcode\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Tensione rete AC nel tempo",
   "type": "timeseries",
   "description": "Indica la tensione della rete in corrente alternata nel corso del tempo",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uac_ac_voltage_v\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Potenza rete AC nel tempo",
   "type": "timeseries",
   "description": "Indica la potenza della rete in corrente alternata nel corso del tempo",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pac_ac_power_w\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Corrente rete AC nel tempo",
   "type": "timeseries",
   "description": "Indica la corrente della rete in corrente alternata nel corso del tempo",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"iac_ac_current_a\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Pannelli fotovoltaici", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Tensione pannello 1 DC",
   "type": "stat",
   "description": "Tensione attuale del pannello 1 in corrente continua",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"udc_dc_voltage_v\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Potenza pannello 1 DC",
   "type": "stat",
   "description": "Potenza attuale del pannello 1 in corrente continua",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"idc_dc_current_a\" or r[\"_field\"] == \"udc_dc_voltage_v\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with _value: r.idc_dc_current_a * r.udc_dc_voltage_v }))\r\n  |> drop(columns: [\"idc_dc_current_a\", \"udc_dc_voltage_v\"])\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Corrente pannello 1 DC",
   "type": "stat",
   "description": "Corrente attuale del pannello 1 in corrente continua",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"idc_dc_current_a\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Tensione pannello 2 DC",
   "type": "stat",
   "description": "Tensione attuale del pannello 2 in corrente continua",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"udc_2_dc_voltage_v\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Potenza pannello 2 DC",
   "type": "stat",
   "description": "Potenza attuale del pannello 2 in corrente continua",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"idc_2_dc_current_a\" or r[\"_field\"] == \"udc_2_dc_voltage_v\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with _value: r.idc_2_dc_current_a * r.udc_2_dc_voltage_v }))\r\n  |> drop(columns: [\"idc_2_dc_current_a\", \"udc_2_dc_voltage_v\"])\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Corrente pannello 2 DC",
   "type": "stat",
   "description": "Corrente attuale del pannello 2 in corrente continua",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"idc_2_dc_current_a\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Tensione pannelli fotovoltaici DC nel tempo",
   "type": "timeseries",
   "description": "Indica la tensione dei pannelli fotovoltaici in corrente continua nel corso del tempo",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"udc_dc_voltage_v\" or r[\"_field\"] == \"udc_2_dc_voltage_v\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Potenza pannelli fotovoltaici DC nel tempo",
   "type": "timeseries",
   "description": "Indica la potenza dei pannelli fotovoltaici in corrente continua nel corso del tempo",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"idc_2_dc_current_a\" or r[\"_field\"] == \"udc_2_dc_voltage_v\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with _value: r.idc_2_dc_current_a * r.udc_2_dc_voltage_v }))\r\n  |> drop(columns: [\"idc_2_dc_current_a\", \"udc_2_dc_voltage_v\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> map(fn: (r) => ({ r with pannello: 2 }))\r\n  |> group(columns: [\"_value\", \"_time\"], mode: \"except\")\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"idc_dc_current_a\" or r[\"_field\"] == \"udc_dc_voltage_v\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with _value: r.idc_dc_current_a * r.udc_dc_voltage_v }))\r\n  |> drop(columns: [\"idc_dc_current_a\", \"udc_dc_voltage_v\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> map(fn: (r) => ({ r with pannello: 1 }))\r\n  |> group(columns: [\"_value\", \"_time\"], mode: \"except\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Corrente pannelli fotovoltaici DC nel tempo",
   "type": "timeseries",
   "description": "Indica la corrente dei pannelli fotovoltaici in corrente continua nel corso del tempo",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket:\"fronius\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_realtime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"idc_dc_current_a\" or r[\"_field\"] == \"idc_2_dc_current_a\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}